version: '3.8'
services:
  planner_dev_db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: planner_dev_db
    networks:
    - home
networks:
  home:

